package com.TT.View;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.tree.DefaultTreeModel;

import net.miginfocom.swing.MigLayout;

import javax.swing.tree.DefaultMutableTreeNode;
//import net.miginfocom.swing.MigLayout;
import java.awt.Component;
import javax.swing.JTextPane;
import javax.swing.JFormattedTextField;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyMTC");
                        getContentPane().setLayout(new MigLayout("", "[100px:150px,grow][25px:25:25px][grow][61px]", "[50][grow][386px,grow][50]"));
                        
                        scrollPane = new JScrollPane();
                        getContentPane().add(scrollPane, "cell 0 2,grow");
                        
                        tree = new JTree();
                        scrollPane.setViewportView(tree);
                        
                                jButton1 = new javax.swing.JButton();
                                
                                        jButton1.setText("Close");
                                        jButton1.addActionListener(new java.awt.event.ActionListener() {
                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                jButton1ActionPerformed(evt);
                                            }
                                        });
                                        
                                        scrollPane_1 = new JScrollPane();
                                        getContentPane().add(scrollPane_1, "cell 2 2,grow");
                                        jTextArea1 = new javax.swing.JTextArea();
                                        scrollPane_1.setViewportView(jTextArea1);
                                        jTextArea1.setColumns(20);
                                        jTextArea1.setLineWrap(true);
                                        jTextArea1.setRows(5);
                                        jTextArea1.setText("TO DO");
                                        jTextArea1.setWrapStyleWord(true);
                                        getContentPane().add(jButton1, "cell 3 3,alignx left,aligny center");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea jTextArea1;
    private JTree tree;
    private JScrollPane scrollPane;
    private JScrollPane scrollPane_1;
    
    // End of variables declaration//GEN-END:variables
}